import { Product, Branch, BlogPost, Testimonial, Category, ContactSubmission } from './types';

export const BRANCHES: Branch[] = [
  {
    id: 't-nagar',
    name: 'T Nagar Main Branch',
    location: 'Chennai, TN',
    address: '45 Ranganathan Street, T Nagar, Chennai, Tamil Nadu 600017',
    phone: '+91 44 1234 5678',
    email: 'tnagar@supersaravana.com',
    hours: '09:00 AM - 10:00 PM',
    image: 'https://picsum.photos/id/101/800/600',
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'purasaiwalkam',
    name: 'Purasaiwalkam Branch',
    location: 'Chennai, TN',
    address: '102 Purasaiwalkam High Rd, Chennai, Tamil Nadu 600010',
    phone: '+91 44 8765 4321',
    email: 'purasai@supersaravana.com',
    hours: '09:30 AM - 09:30 PM',
    image: 'https://picsum.photos/id/102/800/600',
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'chrompet',
    name: 'Chrompet Super Store',
    location: 'Chennai, TN',
    address: '12 GST Road, Chrompet, Chennai, Tamil Nadu 600044',
    phone: '+91 44 1122 3344',
    email: 'chrompet@supersaravana.com',
    hours: '09:00 AM - 10:00 PM',
    image: 'https://picsum.photos/id/103/800/600',
    mapUrl: 'https://maps.google.com',
  },
  {
    id: 'madurai',
    name: 'Madurai Palace',
    location: 'Madurai, TN',
    address: '88 West Masi Street, Madurai, Tamil Nadu 625001',
    phone: '+91 452 555 9999',
    email: 'madurai@supersaravana.com',
    hours: '08:30 AM - 09:30 PM',
    image: 'https://picsum.photos/id/104/800/600',
    mapUrl: 'https://maps.google.com',
  },
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Silk Sarees', slug: 'silk-sarees', image: 'https://picsum.photos/id/21/400/500' },
  { id: '2', name: 'Gold Jewellery', slug: 'jewellery', image: 'https://picsum.photos/id/22/400/500' },
  { id: '3', name: 'Men\'s Wear', slug: 'mens-wear', image: 'https://picsum.photos/id/23/400/500' },
  { id: '4', name: 'Electronics', slug: 'electronics', image: 'https://picsum.photos/id/24/400/500' },
  { id: '5', name: 'Home Appliances', slug: 'home-appliances', image: 'https://picsum.photos/id/25/400/500' },
  { id: '6', name: 'Cosmetics', slug: 'cosmetics', image: 'https://picsum.photos/id/26/400/500' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Kanchipuram Silk Saree',
    category: 'Silk Sarees',
    price: 15000,
    originalPrice: 18000,
    image: 'https://picsum.photos/id/31/600/600',
    description: 'Authentic pure silk saree with zari border, woven by traditional weavers.',
    specs: { Material: 'Pure Silk', Pattern: 'Zari', Color: 'Crimson Red' },
    rating: 4.8,
  },
  {
    id: 'p2',
    name: 'Gold Necklace Set 22k',
    category: 'Jewellery',
    price: 125000,
    image: 'https://picsum.photos/id/32/600/600',
    description: 'Exquisite 22 karat gold necklace with matching earrings. Traditional temple design.',
    specs: { Purity: '22 Karat', Weight: '24 Grams', Design: 'Temple' },
    isNew: true,
    rating: 5.0,
  },
  {
    id: 'p3',
    name: 'Smart LED TV 55"',
    category: 'Electronics',
    price: 45000,
    originalPrice: 65000,
    image: 'https://picsum.photos/id/33/600/600',
    description: '4K Ultra HD Smart LED TV with immersive sound and vibrant display.',
    specs: { Screen: '55 Inch', Resolution: '4K', Warranty: '2 Years' },
    rating: 4.5,
  },
  {
    id: 'p4',
    name: 'Designer Sherwani',
    category: 'Men\'s Wear',
    price: 8999,
    image: 'https://picsum.photos/id/34/600/600',
    description: 'Royal blue sherwani with intricate embroidery, perfect for wedding receptions.',
    specs: { Fabric: 'Velvet', Fit: 'Regular', Occasion: 'Wedding' },
    rating: 4.7,
  },
  {
    id: 'p5',
    name: 'Mixer Grinder 750W',
    category: 'Home Appliances',
    price: 3499,
    originalPrice: 4999,
    image: 'https://picsum.photos/id/35/600/600',
    description: 'Heavy duty mixer grinder with 3 stainless steel jars.',
    specs: { Power: '750W', Jars: '3', Warranty: '1 Year' },
    rating: 4.2,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Aadi Month Mega Sale is Here!',
    snippet: 'Get up to 50% off on textiles and jewellery this Aadi month. Visit our stores...',
    content: 'The Aadi sale is the biggest shopping festival of the year. We bring you exclusive discounts on our entire range of silk sarees, ready-made garments, and home appliances. This year, we are also introducing a special loyalty program for our early bird shoppers. Don’t miss out on the golden opportunity to revamp your wardrobe and your home at unbeatable prices.',
    date: 'July 15, 2024',
    author: 'Marketing Team',
    image: 'https://picsum.photos/id/41/800/400',
  },
  {
    id: 'b2',
    title: 'Trends in Wedding Jewellery 2024',
    snippet: 'Discover the latest designs that are captivating brides this season. From antique...',
    content: 'Wedding jewellery trends are shifting back to roots with a modern twist. Antique finishes and temple jewellery are seeing a massive comeback. At Super Saravana, our artisans have curated a special collection that blends traditional motifs with contemporary lightweight designs, ensuring you look regal without being weighed down.',
    date: 'August 02, 2024',
    author: 'Priya R.',
    image: 'https://picsum.photos/id/42/800/400',
  },
  {
    id: 'b3',
    title: 'New Branch Opening in Coimbatore',
    snippet: 'We are expanding our footprint! Join us for the grand inauguration of our...',
    content: 'We are thrilled to announce the opening of our newest branch in the heart of Coimbatore. Spread across 5 floors, this new store features a dedicated floor for electronics and a rooftop food court. Join us on inauguration day for special gifts and offers.',
    date: 'September 10, 2024',
    author: 'CEO Desk',
    image: 'https://picsum.photos/id/43/800/400',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  { id: 't1', name: 'Lakshmi Narayan', location: 'Chennai', quote: 'The best place for silk sarees. The collection is endless and the prices are very reasonable.', image: 'https://picsum.photos/id/51/100/100' },
  { id: 't2', name: 'Rajesh Kumar', location: 'Madurai', quote: 'Bought all my home appliances from here. Excellent service and delivery was on time.', image: 'https://picsum.photos/id/52/100/100' },
  { id: 't3', name: 'Sarah J.', location: 'Bangalore', quote: 'Visited the T Nagar branch during my trip. It is a shopping paradise!', image: 'https://picsum.photos/id/53/100/100' },
];

export const MOCK_CONTACT_SUBMISSIONS: ContactSubmission[] = [
  {
    id: 'sub1',
    name: 'Ravi Kumar',
    email: 'ravi.k@example.com',
    subject: 'Order Support',
    message: 'I have not received my order #98223 yet. It has been 5 days.',
    date: '2024-10-25',
    isRead: false,
  },
  {
    id: 'sub2',
    name: 'Anita Desai',
    email: 'anita.d@example.com',
    subject: 'Bulk Purchase Inquiry',
    message: 'We are looking to purchase 50 silk sarees for a wedding. Do you offer bulk discounts?',
    date: '2024-10-24',
    isRead: true,
  },
  {
    id: 'sub3',
    name: 'Michael Smith',
    email: 'mike.smith@example.com',
    subject: 'Feedback',
    message: 'Great service at the T Nagar branch! The staff was very helpful.',
    date: '2024-10-22',
    isRead: true,
  },
];